# Generated by Django 5.1.5 on 2025-01-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', 'Peut changer le titre du blog')]},
        ),
    ]
