# Generated by Django 5.1.5 on 2025-01-20 11:22

from django.db import migrations

def set_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')

    for blog in Blog.objects.all():
        blog.contributors.add(blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(set_contributors)
    ]
