# Generated by Django 5.1.5 on 2025-01-20 10:45

from django.db import migrations

def assign_blog_permissions(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_blog = Permission.objects.get(codename='add_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')
    view_blog = Permission.objects.get(codename='view_blog')

    creator_permissions = [
        add_blog,
        change_blog,
        delete_blog,
        view_blog
    ]

    creators = Group.objects.get(name='Creators')
    creators.permissions.set(creator_permissions)

    subscribers = Group.objects.get(name='Subscribers')
    subscribers.permissions.add(view_blog)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20250120_1030'),
    ]

    operations = [
        migrations.RunPython(assign_blog_permissions)
    ]
